name: Check
on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  check:
    name: ${{ matrix.system }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - system: aarch64-darwin
            runner: macos-latest
          - system: aarch64-linux
            runner: ubuntu-24.04-arm
          - system: x86_64-linux
            runner: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0

      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: nixos-nixfmt
          authToken: ${{ github.event_name == 'push' && secrets.CACHIX_AUTH_TOKEN || '' }}
          skipPush: ${{ github.event_name != 'push' }}

      - name: checks
        run: nix-build -A ci --argstr system "${{ matrix.system }}"
