name: Diff
on:
  # Note: it's very important that we don't run code from forks without sandboxing it,
  # because that way anybody could potentially extract repository secrets!
  # We must ensure that no secrets are in any environment variables when running untrusted code, and that no secrets are persisted to disk and accessible to `readFile`
  # when evaluating Nix code
  pull_request_target: # zizmor: ignore[dangerous-triggers]

permissions:
  contents: read

jobs:
  nixpkgs:
    name: Nixpkgs
    runs-on: ubuntu-latest
    # Ensures that we don't run two comment-posting workflows at the same time
    concurrency:
      group: ${{ github.workflow_ref }}-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad # v4.0.0
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Nixpkgs diff

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        id: couc
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            Nixpkgs diff [processing](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})..

            Will be available [here](https://github.com/${{ vars.MACHINE_USER }}/nixpkgs/commits/nixfmt-${{ github.event.pull_request.number }})

      # To prevent running untrusted code from forks,
      # pull_request_target will cause the base branch to be checked out, not the PR branch.
      # This is exactly what we want in this case,
      # because the sync-pr.sh script cannot be run sandboxed since it needs to have side effects.
      # Make sure you do not expose secrets in the environment or persist them to disk
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: cachix/install-nix-action@a49548c11d9846ad46ecc0115273879b045f001c # v31.10.7

      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: nixos-nixfmt
          authToken: ${{ github.event_name == 'push' && secrets.CACHIX_AUTH_TOKEN || '' }}
          skipPush: ${{ github.event_name != 'push' }}

      - run: |
          ./scripts/sync-pr.sh \
            https://github.com/${{ github.repository }} \
            ${{ github.event.pull_request.number }} \
            "https://${{ secrets.MACHINE_USER_PAT }}@github.com/${MACHINE_USER}/nixpkgs"
        env:
          MACHINE_USER: ${{ vars.MACHINE_USER }}

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        with:
          comment-id: ${{ steps.couc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            [Nixpkgs diff](https://github.com/${{ vars.MACHINE_USER }}/nixpkgs/commits/nixfmt-${{ github.event.pull_request.number }})

